import assert from 'node:assert/strict';
import test from 'node:test';
import { createServer as httpsServer } from 'node:https';
import { createServer } from 'node:http';
import { mkdtemp, readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { NativeBridge, createBridgeServer } from '../src/node/bridge.js';
import { DemoModel } from '../src/browser/demo.js';
import type { ModelRequest } from '../src/core.js';

test('HTTPS guide connects a real loopback bridge and Ollama fixture, opens unchanged harness and clears shared state', async t => {
  const scratch = await mkdtemp(path.join(tmpdir(), 'guide-browser-')); t.after(() => rm(scratch, { recursive: true, force: true }));
  const other = await mkdtemp(path.join(tmpdir(), 'guide-other-repo-')); t.after(() => rm(other, { recursive: true, force: true }));
  assert.equal(spawnSync('git', ['init', '-q', other]).status, 0);
  await writeFile(path.join(other, 'AGENTS.md'), 'Use the newly selected repository.');
  const cert = path.join(scratch, 'cert.pem'), key = path.join(scratch, 'key.pem');
  assert.equal(spawnSync('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', key, '-out', cert, '-subj', '/CN=localhost', '-days', '1'], { stdio: 'ignore' }).status, 0);
  const website = httpsServer({ key: await readFile(key), cert: await readFile(cert) }, async (request, response) => {
    try { const file = new URL(request.url!, 'https://localhost').pathname; const body = await readFile(path.resolve('dist/browser', '.' + file)); response.setHeader('Content-Type', file.endsWith('.html') ? 'text/html' : file.endsWith('.json') ? 'application/json' : 'application/javascript'); response.end(body); }
    catch { response.writeHead(404); response.end(); }
  });
  await new Promise<void>(resolve => website.listen(0, '127.0.0.1', resolve)); t.after(() => { website.closeAllConnections(); website.close(); });
  const origin = `https://127.0.0.1:${(website.address() as { port: number }).port}`;
  await writeFile(path.join(scratch, 'AGENTS.md'), 'This is a disposable project.');
  await mkdir(path.join(scratch, 'agents'));
  await writeFile(path.join(scratch, 'agents', 'coder.md'), 'tools: read_file, write_file, run_command\n---\nProject coder: inspect the relevant code before answering.');
  assert.equal(spawnSync('git', ['init', '-q', scratch]).status, 0);
  let failModelDescription = false;
  const model = new DemoModel(), ollama = createServer(async (request, response) => {
    response.setHeader('Access-Control-Allow-Origin', origin); response.setHeader('Access-Control-Allow-Headers', 'Content-Type'); response.setHeader('Access-Control-Allow-Private-Network', 'true');
    if (request.method === 'OPTIONS') { response.end(); return; }
    if (request.url === '/api/tags') { response.end(JSON.stringify({ models: [{ name: 'qwen3:8b' }] })); return; }
    if (request.url === '/api/show') { if (failModelDescription) { response.writeHead(503); response.end('PRIVATE provider response'); return; } response.end(JSON.stringify({ model_info: { 'general.architecture': 'qwen3', 'qwen3.context_length': 8192 } })); return; }
    let body = ''; for await (const chunk of request) body += chunk;
    const payload = JSON.parse(body) as ModelRequest & { _debug_render_only?: boolean };
    if (payload._debug_render_only) { response.end(JSON.stringify({ _debug_info: { rendered_template: 'hello' } })); return; }
    response.setHeader('Content-Type', 'application/x-ndjson'); for await (const chunk of model.streamChat(JSON.parse(body) as ModelRequest)) response.write(chunk + '\n'); response.end();
  });
  await new Promise<void>(resolve => ollama.listen(0, '127.0.0.1', resolve)); t.after(() => { ollama.closeAllConnections(); ollama.close(); });
  let tokenizations = 0;
  const tokenizer = createServer(async (request, response) => {
    if (request.url === '/v1/models') { response.end(JSON.stringify({ data: [{ id: 'qwen3:8b' }] })); return; }
    let body = ''; for await (const chunk of request) body += chunk;
    assert.equal(JSON.parse(body).content, 'hello'); tokenizations++;
    response.end(JSON.stringify({ tokens: [{ id: 42, piece: 'hello' }] }));
  });
  await new Promise<void>(resolve => tokenizer.listen(0, '127.0.0.1', resolve));
  t.after(() => { tokenizer.closeAllConnections(); tokenizer.close(); });
  const tokenizerUrl = `http://127.0.0.1:${(tokenizer.address() as { port: number }).port}`;
  const bridge = new NativeBridge({ workspace: scratch, origin, grants: { writes: true, commands: true, gitWrites: false }, ollamaUrl: `http://127.0.0.1:${(ollama.address() as { port: number }).port}`, tokenizers: { 'qwen3:8b': { url: tokenizerUrl, alias: 'qwen3:8b', identity: 'fixture GGUF' } } }), server = createBridgeServer(bridge);
  const requests: string[] = []; server.on('request', (request, response) => response.on('finish', () => requests.push(request.method + ' ' + request.url + ' ' + response.statusCode)));
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(() => { server.closeAllConnections(); server.close(); });
  const browser = await chromium.launch({ headless: true }); t.after(() => browser.close());
  const context = await browser.newContext({ ignoreHTTPSErrors: true }); await context.grantPermissions(['local-network-access']);
  const page = await context.newPage(); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); page.on('requestfailed', request => errors.push(request.url() + ' ' + request.failure()?.errorText));
  await page.goto(origin + '/guide.html'); assert.equal(await page.locator('#privacy').inputValue(), 'shared');
  await page.locator('#ollama-url').fill(`http://127.0.0.1:${(ollama.address() as { port: number }).port}`); await page.locator('#check-models').click();
  await page.waitForFunction(() => document.getElementById('status')!.textContent!.includes('Models available'));
  await page.locator('#connect-model').click(); await page.waitForFunction(() => document.getElementById('status')!.textContent!.includes('Model connected'));
  const childPromise = context.waitForEvent('page'); await page.locator('#open-harness').click(); const child = await childPromise;
  child.on('pageerror', error => errors.push(error.message));
  await child.waitForFunction(() => document.querySelectorAll('.tool-checkbox').length > 0 && !(document.getElementById('send') as HTMLButtonElement).disabled);
  for (const name of ['web_search', 'run_command', 'git_status']) assert.equal(await child.locator(`.tool-checkbox[value="${name}"]`).count(), 0);
  await page.locator('#bridge-url').fill(`http://127.0.0.1:${(server.address() as { port: number }).port}`); await page.locator('#bridge-code').fill(bridge.code); await page.locator('#connect-bridge').click();
  await page.waitForFunction(() => document.getElementById('status')!.textContent!.includes('Native workspace connected'), undefined, { timeout: 5000 }).catch(async () => { throw new Error((await page.locator('#status').innerText()) + ' requests: ' + requests.join(', ') + ' errors: ' + errors.join(', ')); });
  await child.waitForFunction(() => document.querySelector('.tool-checkbox[value="web_search"]') !== null, undefined, { timeout: 3000 });
  for (const name of ['web_search', 'run_command', 'git_status', 'git_diff', 'git_log', 'git_branch', 'git_checkout', 'git_commit']) assert.equal(await child.locator(`.tool-checkbox[value="${name}"]`).count(), 1);
  assert.match(await child.locator('#browser-mode-label').innerText(), /paired local workspace/);
  await child.locator('#agent').selectOption('coder');
  await child.locator('#explore-view').selectOption('agent');
  await child.waitForFunction(() => document.getElementById('explore')!.textContent!.includes('Project coder: inspect the relevant code before answering.'));
  assert.match(await child.locator('#explore').innerText(), /tools: read_file, write_file, run_command/);
  await child.locator('#agent').selectOption('');
  await child.locator('#input').fill('Write browser-approved.txt: hello'); await child.locator('#send').click();
  await child.getByRole('button', { name: 'Approve', exact: true }).waitFor();
  const buttons = child.getByRole('button', { name: /Allow once|Approve|Allow/ }); await buttons.first().click();
  await child.waitForFunction(() => !(document.getElementById('send') as HTMLButtonElement).disabled);
  assert.equal(await readFile(path.join(scratch, 'browser-approved.txt'), 'utf8'), 'hello\n');
  await child.locator('#explore-view').selectOption('tokens');
  await child.locator('#token-inspect').click();
  await child.getByText('Configured tokenizer · separate tokenization', { exact: true }).waitFor();
  assert.equal(await child.locator('.token-chip').count(), 1);
  await child.locator('.token-chip').click();
  assert.match(await child.locator('#token-details').innerText(), /42/);
  assert.equal(tokenizations, 1);
  await child.locator('#explore-view').selectOption('memory');
  await child.reload();
  await child.waitForFunction(() => document.querySelectorAll('.tool-checkbox').length > 0 && !(document.getElementById('send') as HTMLButtonElement).disabled, undefined, { timeout: 12_000 });
  assert.match(await child.locator('#browser-mode-label').innerText(), /paired local workspace/);
  assert.match(await page.locator('#bridge-status').innerText(), /Native workspace connected|Connected to your local computer/);
  assert.match(await child.locator('#messages').innerText(), /browser-approved.txt/);
  await child.locator('#input').fill('Write after-reload.txt: still connected'); await child.locator('#send').click();
  await child.getByRole('button', { name: 'Approve', exact: true }).click();
  await child.waitForFunction(() => !(document.getElementById('send') as HTMLButtonElement).disabled);
  assert.equal(await readFile(path.join(scratch, 'after-reload.txt'), 'utf8'), 'still connected\n');
  // Inspect a fresh request after reload; cached evidence alone cannot prove bridge handoff.
  await child.locator('#explore-view').selectOption('tokens');
  await child.waitForFunction(() => document.querySelectorAll('#token-request option').length >= 4);
  const latestRequest = await child.locator('#token-request option').last().getAttribute('value');
  await child.locator('#token-request').selectOption(latestRequest!);
  await child.locator('#token-inspect').click();
  await child.getByText('Configured tokenizer · separate tokenization', { exact: true }).waitFor();
  assert.equal(tokenizations, 2);
  failModelDescription = true;
  for (const [view, content] of [['system', /no system prompt selected/], ['agent', /no agent selected/], ['tools', /read_file/], ['template', /Model template unavailable/], ['final', /im_start/]]) {
    await child.locator('#explore-view').selectOption(view as string);
    await child.waitForFunction(pattern => new RegExp(pattern).test(document.getElementById('explore')!.textContent!), (content as RegExp).source);
    if (view === 'template') assert.match(await child.locator('#explore-header').innerText(), /Model template unavailable/);
    assert.ok(!(await child.locator('#explore').innerText()).includes('PRIVATE'));
  }
  failModelDescription = false;
  await child.locator('#explore-view').selectOption('memory');
  await child.locator('#project').fill('/workspace'); await child.locator('#set-project').click();
  await child.waitForFunction(() => document.getElementById('browser-mode-label')!.textContent!.includes('virtual workspace'), undefined, { timeout: 3000 });
  assert.equal(await child.locator('.tool-checkbox[value="run_command"]').count(), 0);
  await child.locator('#project').fill('/bridge-workspace'); await child.locator('#set-project').click();
  await child.waitForFunction(() => document.getElementById('browser-mode-label')!.textContent!.includes('paired local workspace'), undefined, { timeout: 3000 });
  assert.equal(await child.locator('.tool-checkbox[value="run_command"]').count(), 1);
  await child.locator('#project').fill('/missing-project'); await child.locator('#set-project').click();
  await child.waitForFunction(() => document.getElementById('project-error')!.textContent!.includes('does not exist'));
  assert.match(await child.locator('#browser-mode-label').innerText(), /paired local workspace/);
  await child.locator('#input').fill('Write after-project-change.txt: connected'); await child.locator('#send').click();
  await child.getByRole('button', { name: 'Approve', exact: true }).click();
  await child.waitForFunction(() => !(document.getElementById('send') as HTMLButtonElement).disabled);
  assert.equal(await readFile(path.join(scratch, 'after-project-change.txt'), 'utf8'), 'connected\n');
  assert.deepEqual(await page.evaluate(async () => (await indexedDB.databases()).map(database => database.name)), []);
  assert.deepEqual(await context.cookies(), []);
  await page.setViewportSize({ width: 390, height: 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await child.locator('#browser-local-folder').innerText(), 'Choose bridge folder…');
  await child.locator('#browser-local-folder').click();
  await child.locator('#browser-list').getByText('..', { exact: true }).click();
  await child.locator('#browser-list').getByText(path.basename(other) + '/', { exact: true }).click();
  await child.locator('#browser-select').click();
  await child.waitForFunction(folder => (document.getElementById('project') as HTMLInputElement).value === folder && document.getElementById('browser')!.hidden, other);
  assert.equal(await child.locator('.tool-checkbox[value="run_command"]').count(), 1);
  assert.equal(await child.locator('.tool-checkbox[value="git_status"]').count(), 1);
  await child.locator('#input').fill('Run printf CHOSEN_REPO > cwd-check.txt'); await child.locator('#send').click();
  await child.getByRole('button', { name: 'Approve', exact: true }).click();
  await child.waitForFunction(() => !(document.getElementById('send') as HTMLButtonElement).disabled);
  assert.equal(await readFile(path.join(other, 'cwd-check.txt'), 'utf8'), 'CHOSEN_REPO');
  await assert.rejects(readFile(path.join(scratch, 'cwd-check.txt')));
  await page.locator('#disconnect-bridge').click();
  await child.waitForFunction(() => !document.querySelector('.tool-checkbox[value="web_search"]'), undefined, { timeout: 3000 });
  for (const name of ['run_command', 'git_status']) assert.equal(await child.locator(`.tool-checkbox[value="${name}"]`).count(), 0);
  assert.equal(await child.locator('#project').inputValue(), '/workspace');
  assert.match(await child.locator('#browser-mode-label').innerText(), /ready.*virtual workspace/);
  await child.locator('#input').fill('Write after-unpair.txt: browser file'); await child.locator('#send').click();
  await child.getByRole('button', { name: 'Approve', exact: true }).click();
  await child.waitForFunction(() => !(document.getElementById('send') as HTMLButtonElement).disabled);
  const exported = await child.evaluate(async () => (window as unknown as { harness: { call(action: string): Promise<{ files: Record<string, string> }> } }).harness.call('exportProject'));
  assert.equal(exported.files['after-unpair.txt'], 'browser file\n');
  await child.close(); await page.waitForFunction(() => document.getElementById('status')!.textContent!.includes('Session ended'), undefined, { timeout: 5000 }).catch(async () => { throw new Error('After closure: ' + (await page.locator('#status').innerText()) + ' ' + requests.join(', ') + ' ' + errors.join(', ')); });
  // A backend lease failure must replace the Guide's previous success result.
  let connectionNow = 0;
  const secondBridge = new NativeBridge({ workspace: scratch, origin, now: () => connectionNow, grants: { writes: true, commands: true, gitWrites: false } });
  const secondServer = createBridgeServer(secondBridge); await new Promise<void>(resolve => secondServer.listen(0, '127.0.0.1', resolve));
  t.after(() => { secondBridge.close(); secondServer.closeAllConnections(); secondServer.close(); });
  failModelDescription = false; await page.locator('#connect-model').click();
  await page.locator('#bridge-url').fill(`http://127.0.0.1:${(secondServer.address() as { port: number }).port}`);
  await page.locator('#bridge-code').fill(secondBridge.code); await page.locator('#connect-bridge').click();
  await page.waitForFunction(() => document.getElementById('bridge-status')!.textContent!.includes('connected') || document.getElementById('bridge-status')!.textContent!.includes('Connected'));
  const resumedPopup = page.waitForEvent('popup'); await page.locator('#open-harness').click(); const resumedChild = await resumedPopup;
  await resumedChild.waitForFunction(() => document.querySelectorAll('.tool-checkbox[value="run_command"]').length === 1);
  connectionNow = 120_001; secondBridge.sweep(); await page.bringToFront();
  await page.waitForFunction(() => document.getElementById('bridge-status')!.textContent!.includes('disconnected'), undefined, { timeout: 10_000 });
  assert.match(await page.locator('#model-status').innerText(), /Model configured/);
  assert.match(await page.locator('#status').innerText(), /Keep the harness tab open/);
  assert.match(await page.locator('#status').innerText(), /Time limit: 2 minutes/);
  assert.equal(await page.locator('#status details').evaluate(element => (element as HTMLDetailsElement).open), false);
  await resumedChild.waitForFunction(() => document.querySelectorAll('.tool-checkbox[value="run_command"]').length === 0);
  await resumedChild.close();
  assert.deepEqual(errors, []);
});
