#!/usr/bin/env python3
"""Check helper branches, line coverage, and pinned llama.cpp vocabulary goldens.

Usage: python3 native/tokenizer/tests/verify.py --llama-source PATH --helper PATH
Requires g++, gcov and a built real helper. No inference model or Ollama is used.
"""
import argparse
import json
import pathlib
import subprocess
import tempfile
import time

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--llama-source', type=pathlib.Path, required=True)
parser.add_argument('--helper', type=pathlib.Path, required=True)
args = parser.parse_args()
args.llama_source = args.llama_source.resolve()
args.helper = args.helper.resolve()
source = pathlib.Path(__file__).resolve().parents[1]

with tempfile.TemporaryDirectory(prefix='myharness-native-check-') as folder:
    root = pathlib.Path(folder)
    stub = root / 'helper'
    subprocess.run(['g++', '-std=c++17', '--coverage', '-O0', '-I' + str(source / 'tests'),
                    '-I' + str(args.llama_source / 'vendor'), str(source / 'main.cpp'), '-o', str(stub)], check=True)
    def run(argv, data=b''):
        return subprocess.run([str(stub), *argv], input=data, capture_output=True, timeout=30)
    assert run([]).returncode == 2
    assert run(['wrong', 'model']).returncode == 2
    assert run(['-m', 'missing']).returncode == 1
    texts = ['', 'normal', 'positive', 'long', 'overflow', 'bad-count', 'extra-count',
             'piece-overflow', 'piece-limit', 'bad-piece', 'extra-piece', 'retry-piece', 'output']
    lines = [json.dumps({'content': text}) for text in texts] + ['bad JSON', '{}', '{"content":3}']
    result = run(['-m', 'fixture'], ('\n'.join(lines) + '\n').encode())
    assert result.returncode == 0
    responses = [json.loads(line) for line in result.stdout.splitlines()]
    assert responses[0] == {'ready': True, 'protocol': 1, 'vocab_only': True}
    assert responses[1] == {'tokens': []}
    assert responses[2]['tokens'][0]['bytes'] == [0, 255, 255]
    assert len(responses[4]['tokens'][0]['bytes']) == 100
    assert all('error' in response for response in responses[5:])
    assert run(['-m', 'fixture'], b'{').returncode == 1
    assert run(['-m', 'fixture'], b'x' * (8 * 1024 * 1024 + 1)).returncode == 1
    assert run(['-m', 'fixture'], b'x' * (8 * 1024 * 1024) + b'\n').returncode == 0
    subprocess.run(['gcov', '-o', str(root), str(root / 'helper-main.gcno')], cwd=root,
                   check=True, stdout=subprocess.DEVNULL)
    coverage = (root / 'main.cpp.gcov').read_text()
    missed = [line for line in coverage.splitlines() if line.lstrip().startswith('#####')]
    assert not missed, 'Uncovered helper lines: ' + '\n'.join(missed)
    print('Native helper: 100% executable line coverage; all explicit error branches exercised.')

# The pinned upstream corpora are independent expected token IDs, not generated by this helper.
# Avoid their literal control-token examples: upstream goldens use parse_special=false;
# production inspection deliberately uses parse_special=true.
for family in ['qwen2', 'gpt-2', 'llama-spm']:
    file = args.llama_source / 'models' / ('ggml-vocab-' + family + '.gguf')
    samples = pathlib.Path(str(file) + '.inp').read_text().split('\n__ggml_vocab_test__\n')
    expected = pathlib.Path(str(file) + '.out').read_text().splitlines()
    if samples[-1] == '' and len(samples) == len(expected) + 1:
        samples.pop()
    assert len(samples) == len(expected)
    with tempfile.TemporaryFile() as logs:
        started = time.perf_counter()
        process = subprocess.Popen([str(args.helper.resolve()), '-m', str(file.resolve())],
                                   stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=logs)
        assert json.loads(process.stdout.readline())['vocab_only'] is True
        startup_ms = (time.perf_counter() - started) * 1000
        checked = 0
        for text, golden in zip(samples, expected):
            if '<|' in text or '<s>' in text or '</s>' in text:
                continue
            process.stdin.write((json.dumps({'content': text}) + '\n').encode()); process.stdin.flush()
            result = json.loads(process.stdout.readline())
            assert [token['id'] for token in result['tokens']] == [int(x) for x in golden.split()], (family, text)
            assert all(all(0 <= byte <= 255 for byte in token['bytes']) for token in result['tokens'])
            checked += 1
        # Round trip arbitrary bytes via raw token pieces on byte-level BPE.
        if family != 'llama-spm':
            text = 'é\n\t\0😀<|im_start|>user\nBonjour!\n'
            process.stdin.write((json.dumps({'content': text}) + '\n').encode()); process.stdin.flush()
            result = json.loads(process.stdout.readline())
            assert bytes(byte for token in result['tokens'] for byte in token['bytes']) == text.encode()
        process.stdin.close()
        assert process.wait(timeout=10) == 0
        logs.seek(0)
        assert b'vocab only - skipping tensors' in logs.read()
        print(f'{family}: {checked} upstream golden cases passed; vocabulary startup {startup_ms:.1f} ms; tensors skipped.')
